### ISSUE TITLE
Open source port?

### ISSUE THREAD

**Issue by vinisalazar** [grandhawa/MLDSP#1]
Dear @grandhawa,

I recently read your paper presenting ML-DSP and it really sparked my interest. I praise you for making your tool open source. However, MATLAB is very restrictive. I'd like to kindly ask, do you plan on implementing ML-DSP in an open source language, such as Python, Perl, C/C++ or any others?

Thank you very much,

V

**Comment by grandhawa** [comment]
Dear Vini,


Thanks for showing interest in our tool ML-DSP.


Yes, we are currently testing a single executable file with a graphical user interface (implementation is in MATLAB, but this standalone application won't require MATLAB installation or license at the users' end). Hopefully, this will be available sometime in May 2019. We also plan to add Python implementation in the near future.


Thanks,

Gurjit

________________________________

**Comment by vinisalazar** [comment]
Thank you for your reply. A Python implementation will be very appreciated. Best luck in your endeavours.
