### ISSUE TITLE
CGR Representation to be added

### ISSUE THREAD

**Issue by AadharshAadhithya** [grandhawa/MLDSP#2]
Can Chaos game representation be added here..? would love to work on it.

**Comment by grandhawa** [comment]
Hi Aadharsh! Thank you for showing interest in MLDSP. We have incorporated Chaos Game Representation (CGR) as a numerical representation in MLDSP-GUI (a standalone tool that uses the MLDSP pipeline with some additional functionality). The tool is available on SourceForge (https://sourceforge.net/projects/mldsp-gui/). Please note that MLDSP-GUI is available as an executable file and code is hidden. I will update this (MLDSP) repository to include CGR functionality in a few weeks. We are also releasing web-based MLDSP very soon! If you are just looking for the CGR code, it is publically available on the internet in many programming languages. Please let me know if you need further assistance.
